"""cria o esquema inicial

Retrato do banco como ele já era quando o Flask-Migrate entrou no projeto:
as tabelas tinham nascido de `db.create_all()` e a partir daqui passam a ter
histórico versionado.

Bancos que já estavam de pé quando esta migração foi criada — o de
desenvolvimento e o de produção no Neon — não executam este upgrade. Eles
foram carimbados com `flask db stamp`, que grava a versão sem tocar nas
tabelas; rodar o upgrade neles falharia dizendo que a tabela já existe.

Revision ID: 169fedd696d9
Revises: 
Create Date: 2026-08-23 00:12:47.567136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169fedd696d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamado_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamado_prioridade'), ['prioridade'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamado_responsavel_id'), ['responsavel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamado_setor'), ['setor'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamado_status'), ['status'], unique=False)

    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=100), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('log_auditoria')
    with op.batch_alter_table('chamado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamado_status'))
        batch_op.drop_index(batch_op.f('ix_chamado_setor'))
        batch_op.drop_index(batch_op.f('ix_chamado_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_chamado_prioridade'))
        batch_op.drop_index(batch_op.f('ix_chamado_criado_em'))

    op.drop_table('chamado')
    op.drop_table('usuario')
    # ### end Alembic commands ###
