"""adiciona a tabela de tentativas de acesso

Tira da memória do processo a contagem usada pelos limitadores de login, de
troca de senha e de pedidos de redefinição. Ver `models.TentativaAcesso`.

Revision ID: 5995b4db02ca
Revises: 169fedd696d9
Create Date: 2026-08-23 18:36:50.515005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5995b4db02ca'
down_revision = '169fedd696d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tentativa_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escopo', sa.String(length=30), nullable=False),
    sa.Column('chave', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tentativa_acesso', schema=None) as batch_op:
        batch_op.create_index('ix_tentativa_escopo_chave_data', ['escopo', 'chave', 'criado_em'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tentativa_acesso', schema=None) as batch_op:
        batch_op.drop_index('ix_tentativa_escopo_chave_data')

    op.drop_table('tentativa_acesso')
    # ### end Alembic commands ###
