"""adiciona a tabela de anexos

Revision ID: b3ea6a92ffd9
Revises: d141e98118e1
Create Date: 2026-08-30 13:35:26.454858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ea6a92ffd9'
down_revision = 'd141e98118e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamado.id'], ),
    sa.ForeignKeyConstraint(['comentario_id'], ['comentario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anexo')
    # ### end Alembic commands ###
