"""adiciona o token de api do usuario

Revision ID: d141e98118e1
Revises: 5995b4db02ca
Create Date: 2026-08-23 19:16:13.628388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd141e98118e1'
down_revision = '5995b4db02ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_api_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuario_token_api_hash'), ['token_api_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_token_api_hash'))
        batch_op.drop_column('token_api_hash')

    # ### end Alembic commands ###
