"""adiciona o google_id do usuario (login com Google, issue 95)

Revision ID: d835773a6a22
Revises: b15cea77954b
Create Date: 2026-09-23 23:33:27.984092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd835773a6a22'
down_revision = 'b15cea77954b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuario_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_google_id'))
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
